### ISSUE TITLE
Clean up GeoServer data folder for GeoSHAPE build

### ISSUE THREAD

**Issue by ScottEvil** [ROGUE-JCTD/geoserver_data#3]
Right now the GeoSHAPE build includes all of the layers that have built up over time from ROGUE. The default geoserver data folder should go back to being the minimal content to run GeoSHAPE and the amdin/users will add data as needed. The other data, sld, and schema files for the sample data should be optional for people to pick up. 

When this is done, the Readme should be updated to explain it as well.

**Comment by garnertb** [comment]
This is done.
